trigger:
  - kdcp-478-add-deploy-to-function-app

pr:
  - kdcp-478-add-deploy-to-function-app
  - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: azureSubscription
    displayName: Azure Subscription
    type: string
    values:
      - SAP-WWC-Platform-DEV-Connection
      - SAP-WWC-Platform-QA-Connection
      - SAP-WWC-Platform-STAGE-Connection
      - SAP-WWC-Platform-PROD-Connection
    default: SAP-WWC-Platform-DEV-Connection

variables:
  appName: ''

stages:
- stage: Deploy
  jobs:
    - job: DeployJob
      displayName: 'Deploy Job'
      dependsOn: SetAppName
      variables:
        azureSubscription: ${{ parameters.azureSubscription }}

      steps:
        - checkout: self
        - script: |
            if [ "${{ parameters.azureSubscription }}" == "SAP-WWC-Platform-QA-Connection" ]; then
              echo "##vso[task.setvariable variable=appName;isOutput=true]wwc-q-use2-fnapp"
            elif [ "${{ parameters.azureSubscription }}" == "SAP-WWC-Platform-STAGE-Connection" ]; then
              echo "##vso[task.setvariable variable=appName;isOutput=true]wwc-s-use2-fnapp"
            elif [ "${{ parameters.azureSubscription }}" == "SAP-WWC-Platform-PROD-Connection" ]; then
              echo "##vso[task.setvariable variable=appName;isOutput=true]wwc-p-use2-fnapp"
            else
              echo "##vso[task.setvariable variable=appName;isOutput=true]wwc-d-use2-fnapp"
            fi
          displayName: 'Set App Name'

        - script: echo "Selected App Name: $(appName)"
