trigger:
- kdcp-478-add-deploy-to-function-app  

pr:
- kdcp-478-add-deploy-to-function-app
- main  

pool:
  vmImage: 'ubuntu-latest'
  
parameters:
  - name: azureSubscription
    displayName: Azure Subscription
    type: string
    values:
      - SAP-WWC-Platform-DEV-Connection
      - SAP-WWC-Platform-QA-Connection
      - SAP-WWC-Platform-STAGE-Connection
      - SAP-WWC-Platform-PROD-Connection
    default: SAP-WWC-Platform-DEV-Connection

  - name: appName
    displayName: App Name
    type: string
    values: 
      - wwc-d-use2-fnapp
      - wwc-q-use2-fnapp
      - wwc-s-use2-fnapp
      - wwc-p-use2-fnapp
    default: wwc-d-use2-fnapp

stages:
- stage: Deploy
  jobs:

  - job: SetAppName
    displayName: 'Set App Name'
    steps:
    - script: |
        if [ "$(azureSubscription)" == "SAP-WWC-Platform-QA-Connection" ]; then
          echo "##vso[task.setvariable variable=appName]wwc-q-use2-fnapp"
        elif [ "$(azureSubscription)" == "SAP-WWC-Platform-STAGE-Connection" ]; then
          echo "##vso[task.setvariable variable=appName]wwc-s-use2-fnapp"
        elif [ "$(azureSubscription)" == "SAP-WWC-Platform-PROD-Connection" ]; then
          echo "##vso[task.setvariable variable=appName]wwc-p-use2-fnapp"
        else
          echo "##vso[task.setvariable variable=appName]wwc-d-use2-fnapp"
        fi
        echo "Selected Azure Subscription: $(azureSubscription)"
        echo "Selected App Name: $(appName)"
      displayName: 'Set App Name'

  - job: DeployJob
    displayName: 'Deploy Job'
    dependsOn: SetAppName  # Ensure SetAppName job runs first
    steps:
    - checkout: self
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: '$(azureSubscription)'
        appType: 'functionAppLinux'
        appName: '$(appName)'
        package: '$(Pipeline.Workspace)/deploy/deploy_artifact'
        runtimeStack: 'NODE|20.x'
